name: build
on:
  push: 
  workflow_dispatch: 
jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - windows-2019
    runs-on: "${{ matrix.os }}"
    steps:
    - uses: actions/checkout@v2
    - shell: pwsh
      if: "${{ runner.os == 'Windows' }}"
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        $ProgressPreference = 'SilentlyContinue'
        Invoke-Expression (Invoke-RestMethod 'https://chocolatey.org/install.ps1')
        choco install llvm
        choco install make
        $env:Path += ";C:\\Program Files\\LLVM\\bin;C:\\ProgramData\\chocolatey\\bin"
        make
    - shell: bash
      if: "${{ runner.os != 'Windows' }}"
      run: |
        make
    - shell: bash
      run: |
        mkdir -p artifacts/${{ matrix.os }}
        cp *.exe artifacts/${{ matrix.os }}
        cp *.pdb artifacts/${{ matrix.os }} || echo no pdbs
    - uses: actions/upload-artifact@v2.2.2
      with:
        name: artifacts
        path: artifacts
